const CONFIG = {
    titleWeb: 'HELLO CẬU',
    introTitle: 'CẬU À',
    introDesc: 'Cậu à, Tớ có điều này muốn hỏi Cậu,Cậu phải trả lời thật lòng nha!!!',
    btnIntro: '^^HIHI^^',
    title: 'Cậu thích tớ đúng không??? 🥰',
    desc: 'Phải trả lời thật lòng đó nha!!',
    btnYes: 'Thích ơi là thích 🥰',
    btnNo: 'Không đời nào nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại thích mình 🥰 ',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Tại vì tớ dễ thương đúng không, tớ biết ngay mà  😘😘, AHIHI!!!',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'Nếu cậu không phiền thì tớ sẽ ở trong tim cậu nha!!! .',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/messages/t/100004478941570',
}
